version: '3'

services:

  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCassandraCluster
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
    volumes:
      - cassandra-data1:/var/lib/cassandra
    ports:
      - "9042:9042"
    networks:
      - cassandra-net

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCassandraCluster
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack2
    volumes:
      - cassandra-data2:/var/lib/cassandra
    ports:
      - "9043:9042"
    networks:
      - cassandra-net


volumes:
  cassandra-data1:
  cassandra-data2:

networks:
  cassandra-net:
    driver: bridge